Task 1

1) Load tidyverse, DBI, dbplyr and RSQLite packages with library() command

In [ ]:
library(dplyr)
library(DBI)
library(RSQLite)
library(dslabs)
library(tidyverse)

2) We will be using 'gapminder' dataset and we will be spliting this data set in two by naming one dataset as 'gapminder_main' and the other one as 'gapminder_geo'

In [ ]:
data("gapminder")

gapminder_main <- gapminder %>%
  select(country, year, infant_mortality, life_expectancy, fertility, population, gdp)

gapminder_geo <- gapminder %>%
  select(country, continent, region) %>%
  distinct()

3) Create a new connection object by creating a new SQLite db file

In [ ]:
if (file.exists("~/databb/temp/world.db")) file.remove("~/databb/temp/world.db")
sqllitedb_file <- dbConnect(RSQLite::SQLite(), "~/databb/temp/world.db")
dbWriteTable(sqllitedb_file, "main_data", gapminder_main)
dbWriteTable(sqllitedb_file, "geo_data", gapminder_geo)

4) Create lazy query objects to each of the tables in the database (not the original tables, but to the tables imported into the SQLite database)

In [ ]:
main_lazy <- tbl(sqllitedb_file, "main_data")
geo_lazy <- tbl(sqllitedb_file, "geo_data")

5) Create other lazy query object(s) by using select, filter, mutate, group_by, summarise and any join function, using each of them at least once.

In [ ]:
joined_data <- main_lazy %>%
  inner_join(geo_lazy, by = "country")

filtered_data <- joined_data %>%
  filter(year > 2000, continent == "Europe")

mutated_data <- filtered_data %>%
  mutate(population_millions = population / 1000000)

grouped_data <- mutated_data %>%
  group_by(region)

summarised_data <- grouped_data %>%
  summarise(
    avg_life_expectancy = mean(life_expectancy, na.rm = TRUE),
    total_population_millions = sum(population_millions, na.rm = TRUE)
  )

6) There should be a final lazy query object that combines all previous steps into one.

In [ ]:
combined_lazy <- summarised_data %>%
  arrange(desc(avg_life_expectancy))

7) Show the underlying sql query of that object
8) Collect the data into a data.frame/tibble/data.table and preview it by calling the name of the assigned object

In [ ]:
show_query(combined_lazy)

result_df <- collect(combined_lazy)
print(result_df)

Task 2 

1) Create a datetime (POSIXct) or date object in any way you like. It can be a simple vector. You can also use a dataset with such a column.

In [ ]:
date1 <- make_date(2024, 03, 11)

2) Use at least three datetime/date operations/functions as to your liking on this datetime/date object.(We can have floor date of the current month by 'floor_date' with using 'month', We can have first day of the other month by 'ceiling_date' with using 'month' and we can have first day of the current year with using 'year')

In [ ]:
floor_date(date1, "month")

In [ ]:
ceiling_date(date1, "month")

In [ ]:
first_day <- floor_date(date1, "year")
first_day